In [76]:
from httpx import ReadTimeout
import nba_api
import pandas as pd
import time
import pprint
import json
import os
from nba_api.stats.static import players

In [41]:
! pip install langchain_community tiktoken langchain-openai langchainhub chromadb langchain

Defaulting to user installation because normal site-packages is not writeable
Collecting langchain_community
  Using cached langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting tiktoken
  Downloading tiktoken-0.12.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Collecting langchain-openai
  Using cached langchain_openai-1.1.7-py3-none-any.whl.metadata (2.6 kB)
Collecting langchainhub
  Using cached langchainhub-0.1.21-py3-none-any.whl.metadata (659 bytes)
Collecting chromadb
  Using cached chromadb-1.4.1-cp39-abi3-win_amd64.whl.metadata (7.3 kB)
Collecting langchain
  Downloading langchain-1.2.7-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-core<2.0.0,>=1.0.1 (from langchain_community)
  Using cached langchain_core-1.2.7-py3-none-any.whl.metadata (3.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain_community)
  Using cached langchain_classic-1.0.1-py3-none-any.whl.metadata (4.2 kB)
Collecting SQLAlchemy<3.0.0,>=1.4.0 (from langchain_community)
  Downloading sqlalchemy-2.0.46-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from langchain_community) (2.32.5)
Collecting PyYAML<7.0.0,>=5.3.0 (from langchain_community)
  Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from langchain_community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from langchain_community) (9.1.2)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain_community)
  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain_community)
  Downloading pydantic_settings-2.12.0-py3-none-any.whl.metadata (3.4 kB)
Collecting langsmith<1.0.0,>=0.1.125 (from langchain_community)
  Downloading langsmith-0.6.7-py3-none-any.whl.metadata (15 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Using cached httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=1.26.2 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from langchain_community) (2.2.6)
Collecting regex>=2022.1.18 (from tiktoken)
  Downloading regex-2026.1.15-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting openai<3.0.0,>=1.109.1 (from langchain-openai)
  Downloading openai-2.16.0-py3-none-any.whl.metadata (29 kB)
Collecting packaging<25,>=23.2 (from langchainhub)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting types-requests<3.0.0.0,>=2.31.0.2 (from langchainhub)
  Using cached types_requests-2.32.4.20260107-py3-none-any.whl.metadata (2.0 kB)
Collecting build>=1.0.3 (from chromadb)
  Using cached build-1.4.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=1.9 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from chromadb) (2.12.5)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-win_amd64.whl.metadata (9.1 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Using cached uvicorn-0.40.0-py3-none-any.whl.metadata (6.7 kB)
Collecting posthog<6.0.0,>=2.4.0 (from chromadb)
  Using cached posthog-5.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.23.2-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Using cached opentelemetry_api-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Using cached opentelemetry_exporter_otlp_proto_grpc-1.39.1-py3-none-any.whl.metadata (2.5 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Using cached opentelemetry_sdk-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting tokenizers>=0.13.2 (from chromadb)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.0-py2.py3-none-any.whl.metadata (51 kB)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from chromadb) (4.67.1)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting importlib-resources (from chromadb)
  Using cached importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from chromadb) (1.76.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-win_amd64.whl.metadata (10 kB)
Collecting typer>=0.9.0 (from chromadb)
  Downloading typer-0.21.1-py3-none-any.whl.metadata (16 kB)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.2.0-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting orjson>=3.9.12 (from chromadb)
  Downloading orjson-3.11.6-cp312-cp312-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: httpx>=0.27.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from chromadb) (14.2.0)
Collecting jsonschema>=4.19.0 (from chromadb)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting langgraph<1.1.0,>=1.0.7 (from langchain)
  Downloading langgraph-1.0.7-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.22.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Using cached pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain_community)
  Using cached marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain_community)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: anyio in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx>=0.27.0->chromadb) (4.12.0)
Requirement already satisfied: certifi in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx>=0.27.0->chromadb) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.19.0->chromadb)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.19.0->chromadb)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.19.0->chromadb)
  Downloading rpds_py-0.30.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.9.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 (from kubernetes>=28.1.0->chromadb)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting requests-oauthlib (from kubernetes>=28.1.0->chromadb)
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kubernetes>=28.1.0->chromadb) (2.6.2)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Using cached durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain_community)
  Using cached langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.0.1->langchain_community)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.0.1->langchain_community)
  Downloading uuid_utils-0.14.0-cp39-abi3-win_amd64.whl.metadata (5.0 kB)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.1.0,>=1.0.7->langchain)
  Using cached langgraph_checkpoint-4.0.0-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.7 (from langgraph<1.1.0,>=1.0.7->langchain)
  Downloading langgraph_prebuilt-1.0.7-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.1.0,>=1.0.7->langchain)
  Using cached langgraph_sdk-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.1.0,>=1.0.7->langchain)
  Downloading xxhash-3.6.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.1.125->langchain_community)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.1.125->langchain_community)
  Downloading zstandard-0.25.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from onnxruntime>=1.14.1->chromadb) (25.9.23)
Requirement already satisfied: protobuf in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from onnxruntime>=1.14.1->chromadb) (5.29.5)
Requirement already satisfied: sympy in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Collecting jiter<1,>=0.10.0 (from openai<3.0.0,>=1.109.1->langchain-openai)
  Downloading jiter-0.12.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: sniffio in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Collecting importlib-metadata<8.8.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.72.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.39.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Using cached opentelemetry_exporter_otlp_proto_common-1.39.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.39.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Using cached opentelemetry_proto-1.39.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-semantic-conventions==0.60b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Using cached opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl.metadata (2.4 kB)
Collecting backoff>=1.10.0 (from posthog<6.0.0,>=2.4.0->chromadb)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic>=1.9->chromadb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pydantic>=1.9->chromadb) (0.4.2)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain_community)
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Collecting greenlet>=1 (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community)
  Downloading greenlet-3.3.1-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting huggingface-hub<2.0,>=0.16.4 (from tokenizers>=0.13.2->chromadb)
  Downloading huggingface_hub-1.3.5-py3-none-any.whl.metadata (13 kB)
Collecting click>=8.0.0 (from typer>=0.9.0->chromadb)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer>=0.9.0->chromadb)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.7.1-cp312-cp312-win_amd64.whl.metadata (3.6 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.1.1-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: websockets>=10.4 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\natha\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.2.0 (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb)
  Downloading hf_xet-1.2.0-cp37-abi3-win_amd64.whl.metadata (5.0 kB)
Collecting typer-slim (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb)
  Downloading typer_slim-0.21.1-py3-none-any.whl.metadata (16 kB)
Collecting zipp>=3.20 (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain_community)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.7->langchain)
  Downloading ormsgpack-1.12.2-cp312-cp312-win_amd64.whl.metadata (3.3 kB)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.21 requires numpy<2, but you have numpy 2.2.6 which is incompatible.
mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 5.29.5 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\natha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
import os
from dotenv import load_dotenv
load_dotenv()
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = 'https://api.smith.langchain.com'
os.environ['LANGCHAIN_API_KEY'] = os.getenv("LANGCHAIN_API_KEY")
os.environ["OPENAI_API_KEY"] = os.getenv("OPEN_AI_API_KEY")

In [97]:
import sqlite3

# Connect to your local DB
db_path = "data/nba_stats.db"

def get_schema():
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    # Query to get all table names and their CREATE statements
    cursor.execute("SELECT sql FROM sqlite_master WHERE type='table';")
    schema = "\n".join([row[0] for row in cursor.fetchall() if row[0]])
    conn.close()
    return schema

db_schema = get_schema()

In [98]:
import pprint
pprint.pprint(db_schema)
with open('db_schema.txt', 'w') as f:
    f.write(db_schema)

('CREATE TABLE player_season_stats (\n'
 '        player_id INTEGER NOT NULL,\n'
 '        player_name TEXT NOT NULL,\n'
 '        team_id INTEGER,\n'
 '        team_abbreviation TEXT,\n'
 '        season TEXT NOT NULL,\n'
 '        age REAL,\n'
 '        gp INTEGER,\n'
 '        w INTEGER,\n'
 '        l INTEGER,\n'
 '        w_pct REAL,\n'
 '        min REAL,\n'
 '        fgm REAL, fga REAL, fg_pct REAL,\n'
 '        fg3m REAL, fg3a REAL, fg3_pct REAL,\n'
 '        ftm REAL, fta REAL, ft_pct REAL,\n'
 '        oreb REAL, dreb REAL, reb REAL,\n'
 '        ast REAL, tov REAL,\n'
 '        stl REAL, blk REAL, pf REAL,\n'
 '        pts REAL, plus_minus REAL,\n'
 '        ts_pct REAL, efg_pct REAL,\n'
 '        pts_per36 REAL, reb_per36 REAL, ast_per36 REAL,\n'
 '        stl_per36 REAL, blk_per36 REAL,\n'
 '        PRIMARY KEY (player_id, season)\n'
 '    )\n'
 'CREATE TABLE modern_players (player_id INTEGER PRIMARY KEY, full_name TEXT '
 'NOT NULL, is_active INTEGER)\n'
 'CREATE TABLE player_missing_seasons (player_name TEXT, seasons_json TEXT, '
 'missing_seasons_json TEXT)\n'
 'CREATE TABLE draft_history (person_id INTEGER, player_name TEXT, season '
 'TEXT, \n'
 '                   overall_pick INTEGER, team_abbreviation TEXT, '
 'organization TEXT)')

In [99]:
from pydantic import BaseModel, Field
class SQLQueryResult(BaseModel):
    table_name: str = Field(description="The name of the table used in the query")
    query: str = Field(description="The executable SQLite query")
    file_name: str = Field(description="The name of the file used in the query")

In [136]:
from langchain_core.prompts import ChatPromptTemplate

# Custom prompt for SQL generation
sql_template = """You are a SQLite expert. Given the following database schema, 
write a SQL query that answers the user's question. Your response should ACCURATELY reflect the column NAMES and STRUCTURE in the schema. do NOT deviate from this
Also, use context clues from the question to infer any filters that should be applied. Example; someone asking about "KD" should be filtered to "Kevin Durant" in the player_name column, as that is his real name and should be used
Output ONLY the SQL code, no preamble.
Stats that the user asks about (points, rebounds, assists, etc.) should be in the form of "pts", "reb", "ast", etc. as they are in the database, and should be assumed to be in their base form (per game, not per 36 minutes) unless otherwise specified.
Use outside information to transform any nicknames or abbreviations into the correct values in the database.
Additionally, seasons should be in the format "2023-24" for the 2024 season, "2013-14" for the 2014 season, etc. the ONLY exception being if asked about draft YEAR, if someone asks for players drafted in 2020, the draft_year column should be filtered to 2020, not 2019-20.
Percentage stats should be in decimal form, so 50% should be 0.5, 45.3% should be 0.453, etc.
Counting stats are all in their per game form, if a user asks for totals on the season, multiply those stats by games played
IMPORTANT: Always subtract 0.01 from any counting stats, so if the user asks for a specific counting stats, such as "who averaged >=24 ppg", write in the SQL >=23.99 instead of >=24, to account for any rounding issues in the data. Mind this should only be applied to counting stats like points, rebounds, assists, steals and blocks, not percentage stats like shooting percentages, or advanced stats like PER, win shares, etc. 
Here's the order I'd like you to give me the information
1. The table name that is most relevant to the user's question, based on the schema and the question. Only output one table name, and it should be the most relevant one to the user's question. This will be used to determine which table to query from.
2. The SQL query (self explanatory)
3. The file name for the resulting query output (should match the information you gave, so if you were asked to compare lebron and kd, it would be something like "lebron_kd_comparison")

Schema:
{schema}

Question: {question}

SQL Query:"""

sql_prompt = ChatPromptTemplate.from_template(sql_template)

In [120]:
import json
from pathlib import Path

# ---------- path ----------
DRAFT_JSON_PATH = Path("data/draft_history.json")

def fix_json_seasons():
    if not DRAFT_JSON_PATH.exists():
        print(f"File not found: {DRAFT_JSON_PATH}")
        return

    # 1. Load the existing data
    with open(DRAFT_JSON_PATH, 'r') as f:
        data = json.load(f)

    # 2. Update the season format
    # This converts "2024" -> "2023-24" or "2025" -> "2024-25"
    # Adjust the logic if you specifically want "2024-25" for draft year 2025
    for entry in data:
        raw_season = entry.get("SEASON")
        if raw_season and len(raw_season) == 4:
            year = int(raw_season)
            # Typically, the 2024 Draft corresponds to the 2024-25 season
            # If you want the draft year to match the upcoming season:
            formatted = f"{year}-{str(year + 1)[-2:]}"
            entry["SEASON"] = formatted

    # 3. Save it back to the same file
    with open(DRAFT_JSON_PATH, 'w') as f:
        json.dump(data, f, indent=2)

    print(f"✅ Successfully updated seasons in {DRAFT_JSON_PATH}")

if __name__ == "__main__":
    fix_json_seasons()

✅ Successfully updated seasons in data\draft_history.json

In [137]:
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

llm = ChatOpenAI(model_name="gpt-4o", temperature=0)
structured_llm = llm.with_structured_output(SQLQueryResult)
# The chain: Prompt -> LLM -> String Output
sql_chain = sql_prompt | structured_llm

# Define your question
question= "players who've made 175 total threes in a season since 2023-24 "
# Generate the SQL
generated_sql = sql_chain.invoke({"schema": db_schema, "question": question})
pprint.pprint(f"Generated SQL:\n{generated_sql}")

('Generated SQL:\n'
 'table_name=\'player_season_stats\' query="SELECT player_name, season, fg3m * '
 "gp AS total_threes\\nFROM player_season_stats\\nWHERE season >= '2023-24' "
 'AND (fg3m * gp) >= 174.99;" file_name=\'players_175_threes_since_2023\'')

In [138]:
df = pd.read_csv("data/nba_player_stats_2000_2025.csv")
#bub carrington player id is 1642267
df[df['PLAYER_NAME'] == "Bub Carrington"][['PLAYER_ID', 'PLAYER_NAME']]

       PLAYER_ID     PLAYER_NAME
11725    1642267  Bub Carrington

In [139]:
import pandas as pd

# Execute the query and store in a variable
conn = sqlite3.connect(db_path)
df_result = pd.read_sql_query(generated_sql.query, conn)
print(df_result)
conn.close()

           player_name   season  total_threes
0      Anthony Edwards  2023-24         189.6
1    Bogdan Bogdanovic  2023-24         237.0
2       Brandon Miller  2023-24         185.0
3          Buddy Hield  2023-24         218.4
4          CJ McCollum  2023-24         237.6
5           Coby White  2023-24         205.4
6        Corey Kispert  2023-24         184.0
7     D'Angelo Russell  2023-24         228.0
8       Damian Lillard  2023-24         219.0
9         De'Aaron Fox  2023-24         214.6
10     Dejounte Murray  2023-24         202.8
11       Derrick White  2023-24         197.1
12    Donovan Mitchell  2023-24         181.5
13    Donte DiVincenzo  2023-24         283.5
14     Duncan Robinson  2023-24         190.4
15       Fred VanVleet  2023-24         226.3
16      Gary Trent Jr.  2023-24         177.5
17       Grayson Allen  2023-24         202.5
18       Jalen Brunson  2023-24         207.9
19         Jalen Green  2023-24         205.0
20        James Harden  2023-24         187.2
21        Jayson Tatum  2023-24         229.4
22        Jordan Poole  2023-24         187.2
23       Keegan Murray  2023-24         184.8
24       Klay Thompson  2023-24         269.5
25     Lauri Markkanen  2023-24         176.0
26         Luka Doncic  2023-24         287.0
27       Malik Beasley  2023-24         221.2
28  Michael Porter Jr.  2023-24         218.7
29       Mikal Bridges  2023-24         221.4
30         Mike Conley  2023-24         182.4
31         Paul George  2023-24         244.2
32          Sam Hauser  2023-24         197.5
33       Stephen Curry  2023-24         355.2
34    Tim Hardaway Jr.  2023-24         213.3
35   Tyrese Haliburton  2023-24         193.2
36        Tyrese Maxey  2023-24         210.0
37     Anfernee Simons  2024-25         217.0
38     Anthony Edwards  2024-25         323.9
39       Austin Reaves  2024-25         197.1
40         Buddy Hield  2024-25         205.0
41          Coby White  2024-25         214.6
42      Damian Lillard  2024-25         197.2
43      Darius Garland  2024-25         210.0
44       Derrick White  2024-25         266.0
45        Devin Booker  2024-25         180.0
46       Dillon Brooks  2024-25         187.5
47    Donovan Mitchell  2024-25         234.3
48     Duncan Robinson  2024-25         192.4
49      Gary Trent Jr.  2024-25         177.6
50          Isaiah Joe  2024-25         192.4
51         Jalen Green  2024-25         237.8
52        James Harden  2024-25         237.0
53        Jayson Tatum  2024-25         252.0
54        Jordan Poole  2024-25         238.0
55   Julian Champagnie  2024-25         180.4
56       Klay Thompson  2024-25         216.0
57         LaMelo Ball  2024-25         178.6
58         Luka Doncic  2024-25         175.0
59       Malik Beasley  2024-25         319.8
60  Michael Porter Jr.  2024-25         192.5
61            Naz Reid  2024-25         176.0
62       Norman Powell  2024-25         180.0
63    Payton Pritchard  2024-25         256.0
64       Royce O'Neale  2024-25         180.0
65       Stephen Curry  2024-25         308.0
66          Trae Young  2024-25         220.4
67         Tyler Herro  2024-25         254.1
68   Tyrese Haliburton  2024-25         219.0
69         Zach LaVine  2024-25         236.8

In [140]:
import sqlite3

def get_real_schema(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    # This pulls the actual SQL used to create your tables
    cursor.execute("SELECT sql FROM sqlite_master WHERE type='table';")
    schema_details = cursor.fetchall()
    conn.close()
    return "\n".join([row[0] for row in schema_details if row[0]])

actual_schema = get_real_schema("data/nba_stats.db")
print(actual_schema)

CREATE TABLE player_season_stats (
        player_id INTEGER NOT NULL,
        player_name TEXT NOT NULL,
        team_id INTEGER,
        team_abbreviation TEXT,
        season TEXT NOT NULL,
        age REAL,
        gp INTEGER,
        w INTEGER,
        l INTEGER,
        w_pct REAL,
        min REAL,
        fgm REAL, fga REAL, fg_pct REAL,
        fg3m REAL, fg3a REAL, fg3_pct REAL,
        ftm REAL, fta REAL, ft_pct REAL,
        oreb REAL, dreb REAL, reb REAL,
        ast REAL, tov REAL,
        stl REAL, blk REAL, pf REAL,
        pts REAL, plus_minus REAL,
        ts_pct REAL, efg_pct REAL,
        pts_per36 REAL, reb_per36 REAL, ast_per36 REAL,
        stl_per36 REAL, blk_per36 REAL,
        PRIMARY KEY (player_id, season)
    )
CREATE TABLE modern_players (player_id INTEGER PRIMARY KEY, full_name TEXT NOT NULL, is_active INTEGER)
CREATE TABLE player_missing_seasons (player_name TEXT, seasons_json TEXT, missing_seasons_json TEXT)
CREATE TABLE draft_history (person_id INTEGER, player_name TEXT, season TEXT,
                   overall_pick INTEGER, team_abbreviation TEXT, organization TEXT)

In [141]:
import json

evidence_packet = {
    "question": question,
    "row_count": len(df_result),
    "data": df_result.to_dict(orient="records")
}

evidence_json = json.dumps(evidence_packet, ensure_ascii=False, indent=2)

print(evidence_json)

{
  "question": "players who've made 175 total threes in a season since 2023-24 ",
  "row_count": 70,
  "data": [
    {
      "player_name": "Anthony Edwards",
      "season": "2023-24",
      "total_threes": 189.6
    },
    {
      "player_name": "Bogdan Bogdanovic",
      "season": "2023-24",
      "total_threes": 237.0
    },
    {
      "player_name": "Brandon Miller",
      "season": "2023-24",
      "total_threes": 185.0
    },
    {
      "player_name": "Buddy Hield",
      "season": "2023-24",
      "total_threes": 218.4
    },
    {
      "player_name": "CJ McCollum",
      "season": "2023-24",
      "total_threes": 237.6
    },
    {
      "player_name": "Coby White",
      "season": "2023-24",
      "total_threes": 205.4
    },
    {
      "player_name": "Corey Kispert",
      "season": "2023-24",
      "total_threes": 184.0
    },
    {
      "player_name": "D'Angelo Russell",
      "season": "2023-24",
      "total_threes": 228.0
    },
    {
      "player_name": "Damian Lillard",
      "season": "2023-24",
      "total_threes": 219.0
    },
    {
      "player_name": "De'Aaron Fox",
      "season": "2023-24",
      "total_threes": 214.6
    },
    {
      "player_name": "Dejounte Murray",
      "season": "2023-24",
      "total_threes": 202.8
    },
    {
      "player_name": "Derrick White",
      "season": "2023-24",
      "total_threes": 197.10000000000002
    },
    {
      "player_name": "Donovan Mitchell",
      "season": "2023-24",
      "total_threes": 181.5
    },
    {
      "player_name": "Donte DiVincenzo",
      "season": "2023-24",
      "total_threes": 283.5
    },
    {
      "player_name": "Duncan Robinson",
      "season": "2023-24",
      "total_threes": 190.39999999999998
    },
    {
      "player_name": "Fred VanVleet",
      "season": "2023-24",
      "total_threes": 226.3
    },
    {
      "player_name": "Gary Trent Jr.",
      "season": "2023-24",
      "total_threes": 177.5
    },
    {
      "player_name": "Grayson Allen",
      "season": "2023-24",
      "total_threes": 202.5
    },
    {
      "player_name": "Jalen Brunson",
      "season": "2023-24",
      "total_threes": 207.9
    },
    {
      "player_name": "Jalen Green",
      "season": "2023-24",
      "total_threes": 205.0
    },
    {
      "player_name": "James Harden",
      "season": "2023-24",
      "total_threes": 187.20000000000002
    },
    {
      "player_name": "Jayson Tatum",
      "season": "2023-24",
      "total_threes": 229.4
    },
    {
      "player_name": "Jordan Poole",
      "season": "2023-24",
      "total_threes": 187.2
    },
    {
      "player_name": "Keegan Murray",
      "season": "2023-24",
      "total_threes": 184.79999999999998
    },
    {
      "player_name": "Klay Thompson",
      "season": "2023-24",
      "total_threes": 269.5
    },
    {
      "player_name": "Lauri Markkanen",
      "season": "2023-24",
      "total_threes": 176.0
    },
    {
      "player_name": "Luka Doncic",
      "season": "2023-24",
      "total_threes": 287.0
    },
    {
      "player_name": "Malik Beasley",
      "season": "2023-24",
      "total_threes": 221.2
    },
    {
      "player_name": "Michael Porter Jr.",
      "season": "2023-24",
      "total_threes": 218.70000000000002
    },
    {
      "player_name": "Mikal Bridges",
      "season": "2023-24",
      "total_threes": 221.4
    },
    {
      "player_name": "Mike Conley",
      "season": "2023-24",
      "total_threes": 182.4
    },
    {
      "player_name": "Paul George",
      "season": "2023-24",
      "total_threes": 244.2
    },
    {
      "player_name": "Sam Hauser",
      "season": "2023-24",
      "total_threes": 197.5
    },
    {
      "player_name": "Stephen Curry",
      "season": "2023-24",
      "total_threes": 355.2
    },
    {
      "player_name": "Tim Hardaway Jr.",
      "season": "2023-24",
      "total_threes": 213.3
    },
    {
      "player_name": "Tyrese Haliburton",
      "season": "2023-24",
      "total_threes": 193.2
    },
    {
      "player_name": "Tyrese Maxey",
      "season": "2023-24",
      "total_threes": 210.0
    },
    {
      "player_name": "Anfernee Simons",
      "season": "2024-25",
      "total_threes": 217.0
    },
    {
      "player_name": "Anthony Edwards",
      "season": "2024-25",
      "total_threes": 323.9
    },
    {
      "player_name": "Austin Reaves",
      "season": "2024-25",
      "total_threes": 197.10000000000002
    },
    {
      "player_name": "Buddy Hield",
      "season": "2024-25",
      "total_threes": 205.0
    },
    {
      "player_name": "Coby White",
      "season": "2024-25",
      "total_threes": 214.6
    },
    {
      "player_name": "Damian Lillard",
      "season": "2024-25",
      "total_threes": 197.2
    },
    {
      "player_name": "Darius Garland",
      "season": "2024-25",
      "total_threes": 210.0
    },
    {
      "player_name": "Derrick White",
      "season": "2024-25",
      "total_threes": 266.0
    },
    {
      "player_name": "Devin Booker",
      "season": "2024-25",
      "total_threes": 180.0
    },
    {
      "player_name": "Dillon Brooks",
      "season": "2024-25",
      "total_threes": 187.5
    },
    {
      "player_name": "Donovan Mitchell",
      "season": "2024-25",
      "total_threes": 234.29999999999998
    },
    {
      "player_name": "Duncan Robinson",
      "season": "2024-25",
      "total_threes": 192.4
    },
    {
      "player_name": "Gary Trent Jr.",
      "season": "2024-25",
      "total_threes": 177.6
    },
    {
      "player_name": "Isaiah Joe",
      "season": "2024-25",
      "total_threes": 192.4
    },
    {
      "player_name": "Jalen Green",
      "season": "2024-25",
      "total_threes": 237.79999999999998
    },
    {
      "player_name": "James Harden",
      "season": "2024-25",
      "total_threes": 237.0
    },
    {
      "player_name": "Jayson Tatum",
      "season": "2024-25",
      "total_threes": 252.0
    },
    {
      "player_name": "Jordan Poole",
      "season": "2024-25",
      "total_threes": 238.0
    },
    {
      "player_name": "Julian Champagnie",
      "season": "2024-25",
      "total_threes": 180.4
    },
    {
      "player_name": "Klay Thompson",
      "season": "2024-25",
      "total_threes": 216.0
    },
    {
      "player_name": "LaMelo Ball",
      "season": "2024-25",
      "total_threes": 178.6
    },
    {
      "player_name": "Luka Doncic",
      "season": "2024-25",
      "total_threes": 175.0
    },
    {
      "player_name": "Malik Beasley",
      "season": "2024-25",
      "total_threes": 319.8
    },
    {
      "player_name": "Michael Porter Jr.",
      "season": "2024-25",
      "total_threes": 192.5
    },
    {
      "player_name": "Naz Reid",
      "season": "2024-25",
      "total_threes": 176.0
    },
    {
      "player_name": "Norman Powell",
      "season": "2024-25",
      "total_threes": 180.0
    },
    {
      "player_name": "Payton Pritchard",
      "season": "2024-25",
      "total_threes": 256.0
    },
    {
      "player_name": "Royce O'Neale",
      "season": "2024-25",
      "total_threes": 180.0
    },
    {
      "player_name": "Stephen Curry",
      "season": "2024-25",
      "total_threes": 308.0
    },
    {
      "player_name": "Trae Young",
      "season": "2024-25",
      "total_threes": 220.4
    },
    {
      "player_name": "Tyler Herro",
      "season": "2024-25",
      "total_threes": 254.1
    },
    {
      "player_name": "Tyrese Haliburton",
      "season": "2024-25",
      "total_threes": 219.0
    },
    {
      "player_name": "Zach LaVine",
      "season": "2024-25",
      "total_threes": 236.8
    }
  ]
}

In [142]:
import pandas as pd

df = pd.DataFrame(evidence_packet["data"])
pd.set_option("display.max_rows", None)
df

           player_name   season  total_threes
0      Anthony Edwards  2023-24         189.6
1    Bogdan Bogdanovic  2023-24         237.0
2       Brandon Miller  2023-24         185.0
3          Buddy Hield  2023-24         218.4
4          CJ McCollum  2023-24         237.6
5           Coby White  2023-24         205.4
6        Corey Kispert  2023-24         184.0
7     D'Angelo Russell  2023-24         228.0
8       Damian Lillard  2023-24         219.0
9         De'Aaron Fox  2023-24         214.6
10     Dejounte Murray  2023-24         202.8
11       Derrick White  2023-24         197.1
12    Donovan Mitchell  2023-24         181.5
13    Donte DiVincenzo  2023-24         283.5
14     Duncan Robinson  2023-24         190.4
15       Fred VanVleet  2023-24         226.3
16      Gary Trent Jr.  2023-24         177.5
17       Grayson Allen  2023-24         202.5
18       Jalen Brunson  2023-24         207.9
19         Jalen Green  2023-24         205.0
20        James Harden  2023-24         187.2
21        Jayson Tatum  2023-24         229.4
22        Jordan Poole  2023-24         187.2
23       Keegan Murray  2023-24         184.8
24       Klay Thompson  2023-24         269.5
25     Lauri Markkanen  2023-24         176.0
26         Luka Doncic  2023-24         287.0
27       Malik Beasley  2023-24         221.2
28  Michael Porter Jr.  2023-24         218.7
29       Mikal Bridges  2023-24         221.4
30         Mike Conley  2023-24         182.4
31         Paul George  2023-24         244.2
32          Sam Hauser  2023-24         197.5
33       Stephen Curry  2023-24         355.2
34    Tim Hardaway Jr.  2023-24         213.3
35   Tyrese Haliburton  2023-24         193.2
36        Tyrese Maxey  2023-24         210.0
37     Anfernee Simons  2024-25         217.0
38     Anthony Edwards  2024-25         323.9
39       Austin Reaves  2024-25         197.1
40         Buddy Hield  2024-25         205.0
41          Coby White  2024-25         214.6
42      Damian Lillard  2024-25         197.2
43      Darius Garland  2024-25         210.0
44       Derrick White  2024-25         266.0
45        Devin Booker  2024-25         180.0
46       Dillon Brooks  2024-25         187.5
47    Donovan Mitchell  2024-25         234.3
48     Duncan Robinson  2024-25         192.4
49      Gary Trent Jr.  2024-25         177.6
50          Isaiah Joe  2024-25         192.4
51         Jalen Green  2024-25         237.8
52        James Harden  2024-25         237.0
53        Jayson Tatum  2024-25         252.0
54        Jordan Poole  2024-25         238.0
55   Julian Champagnie  2024-25         180.4
56       Klay Thompson  2024-25         216.0
57         LaMelo Ball  2024-25         178.6
58         Luka Doncic  2024-25         175.0
59       Malik Beasley  2024-25         319.8
60  Michael Porter Jr.  2024-25         192.5
61            Naz Reid  2024-25         176.0
62       Norman Powell  2024-25         180.0
63    Payton Pritchard  2024-25         256.0
64       Royce O'Neale  2024-25         180.0
65       Stephen Curry  2024-25         308.0
66          Trae Young  2024-25         220.4
67         Tyler Herro  2024-25         254.1
68   Tyrese Haliburton  2024-25         219.0
69         Zach LaVine  2024-25         236.8

In [ ]:
import pickle 
with open("temp_data/" + generated_sql.table_name + ".csv", "wb") as f:
    pickle.dump(evidence_packet, f)

In [145]:
SYSTEM_RULES = """You are an NBA stats analyst.
You MUST answer using ONLY the evidence provided.
Do NOT use outside knowledge.
Do NOT guess or invent numbers.

Keep the answer factual.
"""

USER_PROMPT = f"""User Question:
{question}

Evidence:
{evidence_json}

Return your answer in EXACTLY this format:

Short Answer: The short, concise answer to the user's question, based ONLY on the evidence provided.
Full Dataset: Answer in the form of a table with appropriate rows and columns, based ONLY on the evidence provided. Pretty much, just format the json file in a readable table format, listing EVERY single row NO SKIPPING (IMPORTANT), don't summarize the data. Do NOT use outside knowledge or guess at any numbers. 
Summary: A comprehensive summary of what the data says in relation to the user's question, based ONLY on the evidence provided. Do NOT use outside knowledge or guess at any numbers.
Source: NBAstats.com

IMPORTANT: Before answering "Not Enough Data", check to make sure that the evidence provided is actually insufficient to answer the question. If the data is relevant but just doesn't directly answer the question, you can still use it to provide a short answer and summary, but just say "Not enough data for a comprehensive answer" or something like that in the summary section. Only say "Not enough data" if there is truly no relevant information in the evidence to even partially answer the question.
"""

llm_answer = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

response = llm_answer.invoke([
    {"role": "system", "content": SYSTEM_RULES},
    {"role": "user", "content": USER_PROMPT}
])

print(response.content)

Short Answer: The players who've made 175 total threes in a season since 2023-24 are Anthony Edwards, Bogdan Bogdanovic, Brandon Miller, Buddy Hield, CJ McCollum, Coby White, Corey Kispert, D'Angelo Russell, Damian Lillard, De'Aaron Fox, Dejounte Murray, Derrick White, Donovan Mitchell, Donte DiVincenzo, Duncan Robinson, Fred VanVleet, Gary Trent Jr., Grayson Allen, Jalen Brunson, Jalen Green, James Harden, Jayson Tatum, Jordan Poole, Keegan Murray, Klay Thompson, Lauri Markkanen, Luka Doncic, Malik Beasley, Michael Porter Jr., Mikal Bridges, Mike Conley, Paul George, Sam Hauser, Stephen Curry, Tim Hardaway Jr., Tyrese Haliburton, and Tyrese Maxey.

Full Dataset:
| Player Name         | Season   | Total Threes |
|---------------------|----------|--------------|
| Anthony Edwards     | 2023-24  | 189.6        |
| Bogdan Bogdanovic   | 2023-24  | 237.0        |
| Brandon Miller      | 2023-24  | 185.0        |
| Buddy Hield         | 2023-24  | 218.4        |
| CJ McCollum         | 2023-24  | 237.6        |
| Coby White          | 2023-24  | 205.4        |
| Corey Kispert       | 2023-24  | 184.0        |
| D'Angelo Russell    | 2023-24  | 228.0        |
| Damian Lillard      | 2023-24  | 219.0        |
| De'Aaron Fox        | 2023-24  | 214.6        |
| Dejounte Murray     | 2023-24  | 202.8        |
| Derrick White       | 2023-24  | 197.1        |
| Donovan Mitchell    | 2023-24  | 181.5        |
| Donte DiVincenzo    | 2023-24  | 283.5        |
| Duncan Robinson     | 2023-24  | 190.4        |
| Fred VanVleet       | 2023-24  | 226.3        |
| Gary Trent Jr.      | 2023-24  | 177.5        |
| Grayson Allen       | 2023-24  | 202.5        |
| Jalen Brunson       | 2023-24  | 207.9        |
| Jalen Green         | 2023-24  | 205.0        |
| James Harden        | 2023-24  | 187.2        |
| Jayson Tatum        | 2023-24  | 229.4        |
| Jordan Poole        | 2023-24  | 187.2        |
| Keegan Murray       | 2023-24  | 184.8        |
| Klay Thompson       | 2023-24  | 269.5        |
| Lauri Markkanen     | 2023-24  | 176.0        |
| Luka Doncic         | 2023-24  | 287.0        |
| Malik Beasley       | 2023-24  | 221.2        |
| Michael Porter Jr.  | 2023-24  | 218.7        |
| Mikal Bridges       | 2023-24  | 221.4        |
| Mike Conley         | 2023-24  | 182.4        |
| Paul George         | 2023-24  | 244.2        |
| Sam Hauser          | 2023-24  | 197.5        |
| Stephen Curry       | 2023-24  | 355.2        |
| Tim Hardaway Jr.    | 2023-24  | 213.3        |
| Tyrese Haliburton   | 2023-24  | 193.2        |
| Tyrese Maxey        | 2023-24  | 210.0        |
| Anfernee Simons     | 2024-25  | 217.0        |
| Anthony Edwards     | 2024-25  | 323.9        |
| Austin Reaves       | 2024-25  | 197.1        |
| Buddy Hield         | 2024-25  | 205.0        |
| Coby White          | 2024-25  | 214.6        |
| Damian Lillard      | 2024-25  | 197.2        |
| Darius Garland      | 2024-25  | 210.0        |
| Derrick White       | 2024-25  | 266.0        |
| Devin Booker        | 2024-25  | 180.0        |
| Dillon Brooks       | 2024-25  | 187.5        |
| Donovan Mitchell    | 2024-25  | 234.3        |
| Duncan Robinson     | 2024-25  | 192.4        |
| Gary Trent Jr.      | 2024-25  | 177.6        |
| Isaiah Joe          | 2024-25  | 192.4        |
| Jalen Green         | 2024-25  | 237.8        |
| James Harden        | 2024-25  | 237.0        |
| Jayson Tatum        | 2024-25  | 252.0        |
| Jordan Poole        | 2024-25  | 238.0        |
| Julian Champagnie   | 2024-25  | 180.4        |
| Klay Thompson       | 2024-25  | 216.0        |
| LaMelo Ball         | 2024-25  | 178.6        |
| Luka Doncic         | 2024-25  | 175.0        |
| Malik Beasley       | 2024-25  | 319.8        |
| Michael Porter Jr.  | 2024-25  | 192.5        |
| Naz Reid            | 2024-25  | 176.0        |
| Norman Powell       | 2024-25  | 180.0        |
| Payton Pritchard    | 2024-25  | 256.0        |
| Royce O'Neale       | 2024-25  | 180.0        |
| Stephen Curry       | 2024-25  | 308.0        |
| Trae Young          | 2024-25  | 220.4        |
| Tyler Herro         | 2024-25  | 254.1        |
| Tyrese Haliburton   | 2024-25  | 219.0        |
| Zach LaVine         | 2024-25  | 236.8        |

Summary: The data provides a list of players who have made 175 total threes in a season since 2023-24. The list includes various players such as Stephen Curry, Damian Lillard, Donovan Mitchell, and others who have achieved this milestone in different seasons.

In [146]:
with open('temp_data/chat_output.txt', 'w') as f:
    f.write(response.content)